# Generated by Django 4.0.5 on 2022-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_chat_author_alter_chat_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
